[build]
  publish = "public"
  command = "npm run build --legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/views/index.ejs"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[functions]
  directory = "functions"
